[package]
name = "verify-groth16"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.20.1", default-features = false }
# risc0-groth16 = { path = "../../../../groth16", default-features = false }
